# Encontros e Palestras

## FEVEREIRO

03/02 - Encontro com Ciência de Dados 
	Link para a gravação:
	Código de Incorporação:


10/02 - Encontro com Protagonismos (Mecnologia)
	Link para a gravação: https://youtu.be/6mg3zbj_wJQ
	Código de Incorporação:
<iframe width="853" height="480" src="https://www.youtube.com/embed/6mg3zbj_wJQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


19/02 - Encontro com Ciência de Dados (Uma gentil introdução à ciência de Dados)
	Link para a gravação: https://youtu.be/FsfJ-ERe3rI
	Código de Incorporação: 
<iframe width="683" height="384" src="https://www.youtube.com/embed/FsfJ-ERe3rI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


24/02 - Encontro com Práticas Investigativas (Palestra com o prof. Hugo Enrique)
	Link para a gravação: https://youtu.be/2XC5fp-J0UI
	Código de Incorporação:
<iframe width="853" height="480" src="https://www.youtube.com/embed/2XC5fp-J0UI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


##	MARÇO

03/03 - Encontro com Protagonismos 

05/03 - Retomada com Ciência de Dados
	Link para a gravação: https://youtu.be/v--UCfc3OQQ
	Código de Incorporação: <iframe width="816" height="441" src="https://www.youtube.com/embed/v--UCfc3OQQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

10/03 - Encontro com Inteligência Artificial (Emprego e População)
	Link para a gravação: https://youtu.be/z9MsvqxC4uY
	Código de Incorporação: 
<iframe width="853" height="480" src="https://www.youtube.com/embed/z9MsvqxC4uY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

13/03 - Encontro com Práticas Investigativas (Que cientista eu quero ser?)
	Link da gravação: https://youtu.be/qim5AdxTXP0
	Código de Incorporação: processando: 
<iframe width="853" height="480" src="https://www.youtube.com/embed/qim5AdxTXP0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


17/03 - Encontro com Ciência de Dados (Construindo uma Base de dados)
Link da gravação: https://youtu.be/YMWk1ZVHpQ0
Código de Incorporação: 
<iframe width="853" height="480" src="https://www.youtube.com/embed/YMWk1ZVHpQ0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


19/03 - Retomada com Inteligência Artificial
Link para gravação: https://youtu.be/6EHVx5rDw6o
Código de Incorporação: 
<iframe width="853" height="480" src="https://www.youtube.com/embed/z9MsvqxC4uY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

23/03 - Encontro com Protagonismos (Mulher no Mercado de Trabalho)
	Link para gravação: https://youtu.be/mh1hrYRu5ks
	Código de Incorporação: 
<iframe width="853" height="480" src="https://www.youtube.com/embed/mh1hrYRu5ks" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

25/03 - Encontro com Práticas Investigativas
	Link para gravação: 
	Código de Incorporação:

30/03 - Encontro com Ciência de Dados - Construindo Uma Base de Dados (Retomada) + Visualização e Ciência de Dados (Encontro)
	Link para gravação: https://youtu.be/tT6_xB47Hss
	Código de Incorporação: 
<iframe width="853" height="480" src="https://www.youtube.com/embed/tT6_xB47Hss" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


## ABRIL

01/04 - Retomada de Protagonismos 
	Link para gravação: https://youtu.be/d1HSSJrAEiU
	Código de Incorporação: 
<iframe width="853" height="480" src="https://www.youtube.com/embed/d1HSSJrAEiU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

06/04 - (Encontro) IA - "Educação e Família: Fato ou Fake?" 

<iframe width="640" height="360" src="https://www.youtube.com/embed/Pzg62m0AwMs" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


08/04 - Retomada de Ciência de Dados (Visualização e Ciência de Dados)
	Link para gravação: https://youtu.be/pbioaYwR89U
	Código de Incorporação:
<iframe width="683" height="384" src="https://www.youtube.com/embed/pbioaYwR89U" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

14/04 - Encontro com Práticas Investigativas (Projetos Científicos)
	Link para gravação: https://youtu.be/fU4gafbfMKM
	Código de Incorporação: 
<iframe width="853" height="480" src="https://www.youtube.com/embed/fU4gafbfMKM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

20/04 - Encontro com Protagonismos (As mentiras que nos contam sobre os indígenas nas escolas)
	Link para gravação: https://youtu.be/_0EpeBdzSwI
	Código de Incorporação: 
<iframe width="853" height="480" src="https://www.youtube.com/embed/_0EpeBdzSwI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

22/04 - Retomada de Práticas Investigativas (Projetos Científicos) 
	Link para gravação: https://youtu.be/cucymY45kw4
	Código de Incorporação:
<iframe width="853" height="480" src="https://www.youtube.com/embed/cucymY45kw4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

27/04 - Encontro com Ciência de Dados (Correlação e Causalidade) 
	Link para gravação: https://youtu.be/ja7g6Z88E74
	Código de Incorporação: 
<iframe width="683" height="384" src="https://www.youtube.com/embed/ja7g6Z88E74" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

29/04 - Retomada de Protagonismos
	Link para gravação: https://youtu.be/0aKCBa0kgj8
	Código de Incorporação: 
<iframe width="853" height="480" src="https://www.youtube.com/embed/0aKCBa0kgj8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## MAIO

03/05 - (Palestra) - Encontro (03/05) - "Deconstruindo formas de pensar": Bate-papo com Roseline Oliveira
	Link para gravação: https://youtu.be/WwKmY8rNzzA
	Código de Incorporação: 
<iframe width="853" height="480" src="https://www.youtube.com/embed/WwKmY8rNzzA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

10/05 - (Palestra) - Encontro (10/05) - "Você sabe cuidar da água?": Bate-papo com Asher Kiperstock
Link para gravação: https://youtu.be/MYz7YJYeQSE
	Código de Incorporação: 
<iframe width="853" height="480" src="https://www.youtube.com/embed/MYz7YJYeQSE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


17/05 - (Palestra) - Encontro (17/05) - "Porque escolhi ser cientista": Bate-papo com Leonardo Souza
Link para gravação: https://youtu.be/WsuQ94YALYE
	Código de Incorporação: 
<iframe width="853" height="480" src="https://www.youtube.com/embed/WsuQ94YALYE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

24/05 - (Palestra) - Encontro (24/05) - "A curiosidade é o pulo do gato" com Geisa Santos
Link para gravação: https://youtu.be/cVQtvbRSp3I
	Código de Incorporação: 
<iframe width="853" height="480" src="https://www.youtube.com/embed/cVQtvbRSp3I" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


## JUNHO

07/06 - (Palestra) - Encontro (07/06) -"Alimentação Saudável" com o Prof. Ramon Nascimento
	Link para gravação: https://www.youtube.com/watch?v=Vohgvb6Kk_U
	Código de Incorporação: <iframe width="853" height="480" src="https://www.youtube.com/embed/Vohgvb6Kk_U" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

14/06 - (Palestra) - Encontro (14/06) -  “Consumo Consciente” com Prof. Fábio Ribeiro
Link para gravação: https://www.youtube.com/watch?v=u8IongyEKo4
	Código de Incorporação: 
<iframe width="853" height="480" src="https://www.youtube.com/embed/u8IongyEKo4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

16/06 - (Encontro) - "Divertida mente das máquinas" 
Raony Maia

<iframe width="640" height="360" src="https://www.youtube.com/embed/dN3j0V4-HLc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

28/06 - (Palestra) - Encontro (28/06) - “Experiências com Hortas Urbanas em Salvador” com Lídice Paraguassu
Link para gravação: https://www.youtube.com/watch?v=4_Ispt8dYeA
	Código de Incorporação: 
<iframe width="853" height="480" src="https://www.youtube.com/embed/4_Ispt8dYeA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


## JULHO

05/07 -  (Palestra) - Encontro (05/07) - “Profissão de Físico” com Prof. Tiago Paes
Link para gravação (parte 1): https://youtu.be/JSfXU_cuFow
Link da gravação (parte 2):  https://youtu.be/3-TrXxk9Nac

Código de Incorporação
parte 1

<iframe width="853" height="480" src="https://www.youtube.com/embed/JSfXU_cuFow" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

parte 2

<iframe width="853" height="480" src="https://www.youtube.com/embed/3-TrXxk9Nac" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


12/07 - (Palestra) Encontro (12/07) - “Sustentabilidade e Economia Circular” com Prof. José Oduque 
Link para gravação: https://youtu.be/PHhSEY6vFTI
	Código de Incorporação: 

<iframe width="853" height="480" src="https://www.youtube.com/embed/PHhSEY6vFTI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


19/07 - (Palestra) - Encontro (19/07) - “Saúde Mental” com Psicojunior (19/07)
	Link para gravação: https://youtu.be/iHEhEg2IOA0
	Código de Incorporação:

<iframe width="853" height="480" src="https://www.youtube.com/embed/iHEhEg2IOA0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


26/07 - (Palestra) - Encontro (26/07) - “As definições de vida foram atualizadas” com prof. Ícaro Bernardes 
	Link para gravação: https://youtu.be/a7QmgxusM0s
	Código de Incorporação:

<iframe width="853" height="480" src="https://www.youtube.com/embed/a7QmgxusM0s" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


## AGOSTO

02/08 - (Palestra) - Encontro (02/08) - “A Era da Informação” com Morgan Nich 
	Link para gravação: https://youtu.be/iNIgVcBTvlY
	Código de Incorporação:

<iframe width="853" height="480" src="https://www.youtube.com/embed/iNIgVcBTvlY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


04/08 - (Palestra) - "Ciência de Dados na Engenharia de Transporte"
Jorge Ubirajara Pedreira Junior  

<iframe width="640" height="360" src="https://www.youtube.com/embed/3kugzT-NuGY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

14/08 - (Encontro) Aula de IA: Emprego e População

<iframe width="640" height="360" src="https://www.youtube.com/embed/LEiWjk_XJYE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


Encontro (16/08) - "Saúde e Probabilidade - Ciência de Dados"
Robson Pessoa, Nicole Príncipe

<iframe width="640" height="360" src="https://www.youtube.com/embed/Hq1gg8OcWfE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>



Palestra (18/08) - Palestra - Como Trabalhar com Tecnologia em Programar


<iframe width="640" height="360" src="https://www.youtube.com/embed/mODO4Pu46Yo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


Encontro (18/08) - Protagonismos (O acesso à saúde para as comunidades vulneráveis no Brasil)

<iframe width="640" height="360" src="https://www.youtube.com/embed/C8klhffaOOI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## SETEMBRO

Encontro (01/09) - Práticas Investigativas - Projetos Científicos na prática

<iframe width="640" height="360" src="https://www.youtube.com/embed/3cCzZk73b1Q" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

Encontro (25/09) - Práticas Investigativas - Acompanhamento dos Projetos Científicos

<iframe width="640" height="360" src="https://www.youtube.com/embed/OgAxpAyqXyw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## OUTUBRO

## NOVEMBRO

## DEZEMBRO



